/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.refactorlabs.cs378.sessions;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum BodyStyle { 
  CHASSIS, CONVERTIBLE, COUPE, HATCHBACK, MINIVAN, PICKUP, SUV, VAN, WAGON, SEDAN  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"BodyStyle\",\"namespace\":\"com.refactorlabs.cs378.sessions\",\"symbols\":[\"CHASSIS\",\"CONVERTIBLE\",\"COUPE\",\"HATCHBACK\",\"MINIVAN\",\"PICKUP\",\"SUV\",\"VAN\",\"WAGON\",\"SEDAN\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
