/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.refactorlabs.cs378.sessions;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum EventSubtype { 
  CONTACT_FORM, MARKET_REPORT, CONTACT_FORM_TYPE, ALTERNATIVE, CONTACT_BANNER, CONTACT_BUTTON, DEALER_PHONE, FEATURES_SECTION, GET_DIRECTIONS, SHOW_MORE_BADGES, TEST_DRIVE_LINK, VEHICLE_HISTORY_REPORT_LINK, ERROR, SUCCESS, BADGE_DETAIL, PHOTO_MODAL, BADGES, FEATURES, ALTERNATIVES, VEHICLE_HISTORY  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EventSubtype\",\"namespace\":\"com.refactorlabs.cs378.sessions\",\"symbols\":[\"CONTACT_FORM\",\"MARKET_REPORT\",\"CONTACT_FORM_TYPE\",\"ALTERNATIVE\",\"CONTACT_BANNER\",\"CONTACT_BUTTON\",\"DEALER_PHONE\",\"FEATURES_SECTION\",\"GET_DIRECTIONS\",\"SHOW_MORE_BADGES\",\"TEST_DRIVE_LINK\",\"VEHICLE_HISTORY_REPORT_LINK\",\"ERROR\",\"SUCCESS\",\"BADGE_DETAIL\",\"PHOTO_MODAL\",\"BADGES\",\"FEATURES\",\"ALTERNATIVES\",\"VEHICLE_HISTORY\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
