/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.refactorlabs.cs378.sessions;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Type { 
  CPO, NEW, USED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Type\",\"namespace\":\"com.refactorlabs.cs378.sessions\",\"symbols\":[\"CPO\",\"NEW\",\"USED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
