/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.refactorlabs.cs378.assign7;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class VinImpressionCounts extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"VinImpressionCounts\",\"namespace\":\"com.refactorlabs.cs378.assign7\",\"fields\":[{\"name\":\"unique_user\",\"type\":\"long\",\"default\":0},{\"name\":\"clicks\",\"type\":[\"null\",{\"type\":\"map\",\"values\":\"long\"}],\"default\":null},{\"name\":\"share_market_report\",\"type\":\"long\",\"default\":0},{\"name\":\"submit_contact_form\",\"type\":\"long\",\"default\":0},{\"name\":\"unique_user_vdp_view\",\"type\":\"long\",\"default\":0}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public long unique_user;
  @Deprecated public java.util.Map<java.lang.CharSequence,java.lang.Long> clicks;
  @Deprecated public long share_market_report;
  @Deprecated public long submit_contact_form;
  @Deprecated public long unique_user_vdp_view;

  /**
   * Default constructor.
   */
  public VinImpressionCounts() {}

  /**
   * All-args constructor.
   */
  public VinImpressionCounts(java.lang.Long unique_user, java.util.Map<java.lang.CharSequence,java.lang.Long> clicks, java.lang.Long share_market_report, java.lang.Long submit_contact_form, java.lang.Long unique_user_vdp_view) {
    this.unique_user = unique_user;
    this.clicks = clicks;
    this.share_market_report = share_market_report;
    this.submit_contact_form = submit_contact_form;
    this.unique_user_vdp_view = unique_user_vdp_view;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return unique_user;
    case 1: return clicks;
    case 2: return share_market_report;
    case 3: return submit_contact_form;
    case 4: return unique_user_vdp_view;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: unique_user = (java.lang.Long)value$; break;
    case 1: clicks = (java.util.Map<java.lang.CharSequence,java.lang.Long>)value$; break;
    case 2: share_market_report = (java.lang.Long)value$; break;
    case 3: submit_contact_form = (java.lang.Long)value$; break;
    case 4: unique_user_vdp_view = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'unique_user' field.
   */
  public java.lang.Long getUniqueUser() {
    return unique_user;
  }

  /**
   * Sets the value of the 'unique_user' field.
   * @param value the value to set.
   */
  public void setUniqueUser(java.lang.Long value) {
    this.unique_user = value;
  }

  /**
   * Gets the value of the 'clicks' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.Long> getClicks() {
    return clicks;
  }

  /**
   * Sets the value of the 'clicks' field.
   * @param value the value to set.
   */
  public void setClicks(java.util.Map<java.lang.CharSequence,java.lang.Long> value) {
    this.clicks = value;
  }

  /**
   * Gets the value of the 'share_market_report' field.
   */
  public java.lang.Long getShareMarketReport() {
    return share_market_report;
  }

  /**
   * Sets the value of the 'share_market_report' field.
   * @param value the value to set.
   */
  public void setShareMarketReport(java.lang.Long value) {
    this.share_market_report = value;
  }

  /**
   * Gets the value of the 'submit_contact_form' field.
   */
  public java.lang.Long getSubmitContactForm() {
    return submit_contact_form;
  }

  /**
   * Sets the value of the 'submit_contact_form' field.
   * @param value the value to set.
   */
  public void setSubmitContactForm(java.lang.Long value) {
    this.submit_contact_form = value;
  }

  /**
   * Gets the value of the 'unique_user_vdp_view' field.
   */
  public java.lang.Long getUniqueUserVdpView() {
    return unique_user_vdp_view;
  }

  /**
   * Sets the value of the 'unique_user_vdp_view' field.
   * @param value the value to set.
   */
  public void setUniqueUserVdpView(java.lang.Long value) {
    this.unique_user_vdp_view = value;
  }

  /** Creates a new VinImpressionCounts RecordBuilder */
  public static com.refactorlabs.cs378.assign7.VinImpressionCounts.Builder newBuilder() {
    return new com.refactorlabs.cs378.assign7.VinImpressionCounts.Builder();
  }
  
  /** Creates a new VinImpressionCounts RecordBuilder by copying an existing Builder */
  public static com.refactorlabs.cs378.assign7.VinImpressionCounts.Builder newBuilder(com.refactorlabs.cs378.assign7.VinImpressionCounts.Builder other) {
    return new com.refactorlabs.cs378.assign7.VinImpressionCounts.Builder(other);
  }
  
  /** Creates a new VinImpressionCounts RecordBuilder by copying an existing VinImpressionCounts instance */
  public static com.refactorlabs.cs378.assign7.VinImpressionCounts.Builder newBuilder(com.refactorlabs.cs378.assign7.VinImpressionCounts other) {
    return new com.refactorlabs.cs378.assign7.VinImpressionCounts.Builder(other);
  }
  
  /**
   * RecordBuilder for VinImpressionCounts instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<VinImpressionCounts>
    implements org.apache.avro.data.RecordBuilder<VinImpressionCounts> {

    private long unique_user;
    private java.util.Map<java.lang.CharSequence,java.lang.Long> clicks;
    private long share_market_report;
    private long submit_contact_form;
    private long unique_user_vdp_view;

    /** Creates a new Builder */
    private Builder() {
      super(com.refactorlabs.cs378.assign7.VinImpressionCounts.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.refactorlabs.cs378.assign7.VinImpressionCounts.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing VinImpressionCounts instance */
    private Builder(com.refactorlabs.cs378.assign7.VinImpressionCounts other) {
            super(com.refactorlabs.cs378.assign7.VinImpressionCounts.SCHEMA$);
      if (isValidValue(fields()[0], other.unique_user)) {
        this.unique_user = data().deepCopy(fields()[0].schema(), other.unique_user);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.clicks)) {
        this.clicks = data().deepCopy(fields()[1].schema(), other.clicks);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.share_market_report)) {
        this.share_market_report = data().deepCopy(fields()[2].schema(), other.share_market_report);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.submit_contact_form)) {
        this.submit_contact_form = data().deepCopy(fields()[3].schema(), other.submit_contact_form);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.unique_user_vdp_view)) {
        this.unique_user_vdp_view = data().deepCopy(fields()[4].schema(), other.unique_user_vdp_view);
        fieldSetFlags()[4] = true;
      }
    }

    /** Gets the value of the 'unique_user' field */
    public java.lang.Long getUniqueUser() {
      return unique_user;
    }
    
    /** Sets the value of the 'unique_user' field */
    public com.refactorlabs.cs378.assign7.VinImpressionCounts.Builder setUniqueUser(long value) {
      validate(fields()[0], value);
      this.unique_user = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'unique_user' field has been set */
    public boolean hasUniqueUser() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'unique_user' field */
    public com.refactorlabs.cs378.assign7.VinImpressionCounts.Builder clearUniqueUser() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'clicks' field */
    public java.util.Map<java.lang.CharSequence,java.lang.Long> getClicks() {
      return clicks;
    }
    
    /** Sets the value of the 'clicks' field */
    public com.refactorlabs.cs378.assign7.VinImpressionCounts.Builder setClicks(java.util.Map<java.lang.CharSequence,java.lang.Long> value) {
      validate(fields()[1], value);
      this.clicks = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'clicks' field has been set */
    public boolean hasClicks() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'clicks' field */
    public com.refactorlabs.cs378.assign7.VinImpressionCounts.Builder clearClicks() {
      clicks = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'share_market_report' field */
    public java.lang.Long getShareMarketReport() {
      return share_market_report;
    }
    
    /** Sets the value of the 'share_market_report' field */
    public com.refactorlabs.cs378.assign7.VinImpressionCounts.Builder setShareMarketReport(long value) {
      validate(fields()[2], value);
      this.share_market_report = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'share_market_report' field has been set */
    public boolean hasShareMarketReport() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'share_market_report' field */
    public com.refactorlabs.cs378.assign7.VinImpressionCounts.Builder clearShareMarketReport() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'submit_contact_form' field */
    public java.lang.Long getSubmitContactForm() {
      return submit_contact_form;
    }
    
    /** Sets the value of the 'submit_contact_form' field */
    public com.refactorlabs.cs378.assign7.VinImpressionCounts.Builder setSubmitContactForm(long value) {
      validate(fields()[3], value);
      this.submit_contact_form = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'submit_contact_form' field has been set */
    public boolean hasSubmitContactForm() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'submit_contact_form' field */
    public com.refactorlabs.cs378.assign7.VinImpressionCounts.Builder clearSubmitContactForm() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'unique_user_vdp_view' field */
    public java.lang.Long getUniqueUserVdpView() {
      return unique_user_vdp_view;
    }
    
    /** Sets the value of the 'unique_user_vdp_view' field */
    public com.refactorlabs.cs378.assign7.VinImpressionCounts.Builder setUniqueUserVdpView(long value) {
      validate(fields()[4], value);
      this.unique_user_vdp_view = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'unique_user_vdp_view' field has been set */
    public boolean hasUniqueUserVdpView() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'unique_user_vdp_view' field */
    public com.refactorlabs.cs378.assign7.VinImpressionCounts.Builder clearUniqueUserVdpView() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public VinImpressionCounts build() {
      try {
        VinImpressionCounts record = new VinImpressionCounts();
        record.unique_user = fieldSetFlags()[0] ? this.unique_user : (java.lang.Long) defaultValue(fields()[0]);
        record.clicks = fieldSetFlags()[1] ? this.clicks : (java.util.Map<java.lang.CharSequence,java.lang.Long>) defaultValue(fields()[1]);
        record.share_market_report = fieldSetFlags()[2] ? this.share_market_report : (java.lang.Long) defaultValue(fields()[2]);
        record.submit_contact_form = fieldSetFlags()[3] ? this.submit_contact_form : (java.lang.Long) defaultValue(fields()[3]);
        record.unique_user_vdp_view = fieldSetFlags()[4] ? this.unique_user_vdp_view : (java.lang.Long) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
